# Generated by Django 3.2.3 on 2021-06-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=40),
        ),
    ]
