# Generated by Django 3.2.3 on 2021-06-20 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_newslettersub'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersub',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date subscribed'),
            preserve_default=False,
        ),
    ]
