# Generated by Django 3.2.3 on 2021-05-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
