# Generated by Django 3.2.3 on 2021-05-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210525_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
            },
        ),
    ]
