# Generated by Django 3.2.3 on 2021-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(20, '★☆☆☆☆'), (40, '★★☆☆☆'), (60, '★★★☆☆'), (80, '★★★★☆'), (100, '★★★★★')]),
        ),
    ]
