# Generated by Django 3.2.3 on 2021-05-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_feature_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('ordering', 'parent', 'title'), 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('ordering', 'parent', 'title'), 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AddField(
            model_name='feature',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
