# Generated by Django 3.2.3 on 2021-05-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210526_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('parent', 'ordering', 'title'), 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('parent', 'ordering', 'title'), 'verbose_name_plural': 'Subcategories'},
        ),
    ]
