# Generated by Django 3.2.3 on 2021-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20210526_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(related_name='feature_items', to='products.Feature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(related_name='subcategory_items', to='products.Subcategory'),
        ),
    ]
