# Generated by Django 3.2.3 on 2021-05-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_rating_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(20, 'One Star'), (40, 'Two Star'), (60, 'Three Star'), (80, 'Four Star'), (100, 'Five Star')]),
        ),
    ]
