# Generated by Django 3.2.3 on 2021-05-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210530_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(20, '⭐'), (40, '⭐⭐'), (60, '⭐⭐⭐'), (80, '⭐⭐⭐⭐'), (100, '⭐⭐⭐⭐⭐')]),
        ),
    ]
