# Generated by Django 4.1.3 on 2023-01-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_product_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                limit_choices_to={
                    "parent": models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategory",
                to="products.subcategory",
            ),
        ),
    ]
